In [188]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import set_config
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, OrdinalEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.model_selection import train_test_split

In [189]:
accounts = pd.read_csv('ravenstack_accounts.csv')
churn_events = pd.read_csv('ravenstack_churn_events.csv')
feature_usage = pd.read_csv('ravenstack_feature_usage.csv')
subscription = pd.read_csv('ravenstack_subscriptions.csv')
support = pd.read_csv('ravenstack_support_tickets.csv')

In [190]:
accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    object
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), object(7)
memory usage: 32.4+ KB

In [191]:
churn_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    object
 1   account_id                600 non-null    object
 2   churn_date                600 non-null    object
 3   reason_code               600 non-null    object
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    object
dtypes: bool(3), float64(1), object(5)
memory usage: 30.0+ KB

In [192]:
feature_usage.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   usage_id             25000 non-null  object
 1   subscription_id      25000 non-null  object
 2   usage_date           25000 non-null  object
 3   feature_name         25000 non-null  object
 4   usage_count          25000 non-null  int64
 5   usage_duration_secs  25000 non-null  int64
 6   error_count          25000 non-null  int64
 7   is_beta_feature      25000 non-null  bool
dtypes: bool(1), int64(3), object(4)
memory usage: 1.4+ MB

In [193]:
subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   subscription_id    5000 non-null   object
 1   account_id         5000 non-null   object
 2   start_date         5000 non-null   object
 3   end_date           486 non-null    object
 4   plan_tier          5000 non-null   object
 5   seats              5000 non-null   int64
 6   mrr_amount         5000 non-null   int64
 7   arr_amount         5000 non-null   int64
 8   is_trial           5000 non-null   bool
 9   upgrade_flag       5000 non-null   bool
 10  downgrade_flag     5000 non-null   bool
 11  churn_flag         5000 non-null   bool
 12  billing_frequency  5000 non-null   object
 13  auto_renew_flag    5000 non-null   bool
dtypes: bool(5), int64(3), object(6)
memory usage: 376.1+ KB

In [194]:
support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ticket_id                    2000 non-null   object
 1   account_id                   2000 non-null   object
 2   submitted_at                 2000 non-null   object
 3   closed_at                    2000 non-null   object
 4   resolution_time_hours        2000 non-null   float64
 5   priority                     2000 non-null   object
 6   first_response_time_minutes  2000 non-null   int64
 7   satisfaction_score           1175 non-null   float64
 8   escalation_flag              2000 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(5)
memory usage: 127.1+ KB

In [195]:
accounts['industry'].unique()

array(['EdTech', 'FinTech', 'DevTools', 'HealthTech', 'Cybersecurity'],
      dtype=object)

In [196]:
accounts['country'].unique()

array(['US', 'IN', 'UK', 'CA', 'DE', 'AU', 'FR'], dtype=object)

In [197]:
accounts['referral_source'].unique()

array(['partner', 'other', 'organic', 'event', 'ads'], dtype=object)

In [198]:
accounts['plan_tier'].unique()

array(['Basic', 'Enterprise', 'Pro'], dtype=object)

In [199]:
churn_events.sample(2)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
88,C-f24343,A-425e76,2023-09-03,budget,0.00,False,False,True,missing features
216,C-02a354,A-ccb686,2024-11-24,competitor,25.92,False,False,False,NaN

In [200]:
churn_events['churn_date'] = pd.to_datetime(churn_events['churn_date'])

In [201]:
churn_events_cpy = pd.get_dummies(churn_events, columns=['reason_code', 'feedback_text'], dtype=int)
churn_events_cpy.drop(columns=['churn_event_id'], inplace=True)
churn_events_cpy.sample(2)

,account_id,churn_date,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,reason_code_budget,reason_code_competitor,reason_code_features,reason_code_pricing,reason_code_support,reason_code_unknown,feedback_text_missing features,feedback_text_switched to competitor,feedback_text_too expensive
390,A-34ea2f,2024-10-19,1.85,True,False,False,0,0,0,0,0,1,0,0,1
26,A-034368,2024-08-29,0.00,True,False,False,0,0,1,0,0,0,0,0,0

In [202]:
churn_events_cpy.rename(columns={
    'feedback_text_missing features': 'feedback_text_missing_features',
    'feedback_text_switched to competitor': 'feedback_text_switched_to_competitor',
    'feedback_text_too expensive': 'feedback_text_too_expensive'
}, inplace=True)

In [203]:
churn_events_cpy.columns

Index(['account_id', 'churn_date', 'refund_amount_usd',
       'preceding_upgrade_flag', 'preceding_downgrade_flag', 'is_reactivation',
       'reason_code_budget', 'reason_code_competitor', 'reason_code_features',
       'reason_code_pricing', 'reason_code_support', 'reason_code_unknown',
       'feedback_text_missing_features',
       'feedback_text_switched_to_competitor', 'feedback_text_too_expensive'],
      dtype='object')

In [204]:
churn_events_cpy

,account_id,churn_date,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,reason_code_budget,reason_code_competitor,reason_code_features,reason_code_pricing,reason_code_support,reason_code_unknown,feedback_text_missing_features,feedback_text_switched_to_competitor,feedback_text_too_expensive
0,A-c37cab,2024-10-27,4.03,False,False,False,0,0,0,1,0,0,0,1,0
1,A-37f969,2024-06-25,96.45,True,False,False,0,0,0,0,1,0,0,0,0
2,A-b07346,2024-11-12,0.00,False,False,False,1,0,0,0,0,0,1,0,0
3,A-1e50e0,2023-11-01,54.94,False,False,False,1,0,0,0,0,0,0,1,0
4,A-956988,2024-12-30,0.00,False,True,True,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,A-702032,2024-06-14,0.00,False,False,False,0,1,0,0,0,0,0,1,0
596,A-dbc825,2024-02-03,0.00,False,False,False,1,0,0,0,0,0,0,0,0
597,A-0a282f,2024-12-31,62.66,False,True,False,0,0,0,0,1,0,0,0,1
598,A-e5d6ab,2024-05-11,0.00,True,False,False,0,1,0,0,0,0,0,0,0
599,A-1f559b,2024-09-28,0.00,False,False,False,0,0,1,0,0,0,0,0,0

In [205]:
churn_events_cpy = churn_events_cpy.groupby('account_id').agg({
    'churn_date': 'max',
    'refund_amount_usd': 'sum',
    'preceding_upgrade_flag': 'sum',
    'preceding_downgrade_flag': 'sum',
    'is_reactivation' : 'sum',
    'reason_code_budget': 'sum',
    'reason_code_competitor': 'sum',
    'reason_code_features': 'sum',
    'reason_code_pricing': 'sum',
    'reason_code_support': 'sum',
    'reason_code_unknown': 'sum',
    'feedback_text_missing_features': 'sum',
    'feedback_text_switched_to_competitor': 'sum',
    'feedback_text_too_expensive': 'sum'}).reset_index()

In [206]:
final_df = accounts.merge(churn_events_cpy, on='account_id', how='left')

In [207]:
final_df['account_id'].nunique()

500

In [208]:
final_df

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag,...,is_reactivation,reason_code_budget,reason_code_competitor,reason_code_features,reason_code_pricing,reason_code_support,reason_code_unknown,feedback_text_missing_features,feedback_text_switched_to_competitor,feedback_text_too_expensive
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,A-8ae3fc,Company_495,DevTools,CA,2024-06-28,ads,Pro,9,False,False,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
496,A-55f257,Company_496,FinTech,US,2023-12-21,organic,Basic,9,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,A-d26ab4,Company_497,DevTools,UK,2024-11-07,organic,Basic,9,False,True,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
498,A-712533,Company_498,EdTech,US,2023-07-31,organic,Pro,18,False,False,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
499,A-781cc0,Company_499,EdTech,US,2024-09-04,organic,Pro,12,False,False,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0

In [209]:
feature_usage.sample(2)

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
4012,U-d24ea6,S-510e07,2024-08-20,feature_23,12,1152,0,True
19939,U-d3c8c0,S-519f1c,2023-06-19,feature_23,12,2280,4,False

In [210]:
subscription.sample(2)

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
4514,S-2c3b6d,A-a2485e,2024-12-05,NaN,Enterprise,17,3383,40596,False,False,False,False,annual,True
565,S-b8daaa,A-4bfa33,2024-12-25,NaN,Enterprise,8,0,0,True,False,False,False,annual,True

In [211]:
subscription['subscription_id'].nunique()

5000

In [212]:
feature_usage['subscription_id'].nunique()

4967

In [213]:
feature_usage['usage_date'] = pd.to_datetime(feature_usage['usage_date'])

In [214]:
feature_usage_cpy = pd.get_dummies(feature_usage, columns=['feature_name'], dtype=int)
feature_usage_cpy.drop(columns=['usage_id'], inplace=True)
feature_usage_cpy.sample(2)

,subscription_id,usage_date,usage_count,usage_duration_secs,error_count,is_beta_feature,feature_name_feature_1,feature_name_feature_10,feature_name_feature_11,feature_name_feature_12,...,feature_name_feature_37,feature_name_feature_38,feature_name_feature_39,feature_name_feature_4,feature_name_feature_40,feature_name_feature_5,feature_name_feature_6,feature_name_feature_7,feature_name_feature_8,feature_name_feature_9
1033,S-f703bd,2024-11-12,6,3498,0,False,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15987,S-a1d6ad,2024-02-11,7,805,0,False,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [215]:
cols_to_sum = feature_usage_cpy.columns.difference(['subscription_id', 'usage_date'])
feature_usage_cpy = feature_usage_cpy.groupby('subscription_id').agg({
    'usage_date': 'max',
    **{col: 'sum' for col in cols_to_sum}
}).reset_index()

In [216]:
subscription = subscription.merge(feature_usage_cpy, on='subscription_id', how='left')

In [217]:
subscription['billing_frequency']

0       monthly
1       monthly
2        annual
3       monthly
4       monthly
         ...
4995    monthly
4996    monthly
4997     annual
4998    monthly
4999    monthly
Name: billing_frequency, Length: 5000, dtype: object

In [218]:
subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 59 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   subscription_id          5000 non-null   object
 1   account_id               5000 non-null   object
 2   start_date               5000 non-null   object
 3   end_date                 486 non-null    object
 4   plan_tier                5000 non-null   object
 5   seats                    5000 non-null   int64
 6   mrr_amount               5000 non-null   int64
 7   arr_amount               5000 non-null   int64
 8   is_trial                 5000 non-null   bool
 9   upgrade_flag             5000 non-null   bool
 10  downgrade_flag           5000 non-null   bool
 11  churn_flag               5000 non-null   bool
 12  billing_frequency        5000 non-null   object
 13  auto_renew_flag          5000 non-null   bool
 14  usage_date               4967 non-null   datetime64[ns]
 15  error_count              4967 non-null   float64
 16  feature_name_feature_1   4967 non-null   float64
 17  feature_name_feature_10  4967 non-null   float64
 18  feature_name_feature_11  4967 non-null   float64
 19  feature_name_feature_12  4967 non-null   float64
 20  feature_name_feature_13  4967 non-null   float64
 21  feature_name_feature_14  4967 non-null   float64
 22  feature_name_feature_15  4967 non-null   float64
 23  feature_name_feature_16  4967 non-null   float64
 24  feature_name_feature_17  4967 non-null   float64
 25  feature_name_feature_18  4967 non-null   float64
 26  feature_name_feature_19  4967 non-null   float64
 27  feature_name_feature_2   4967 non-null   float64
 28  feature_name_feature_20  4967 non-null   float64
 29  feature_name_feature_21  4967 non-null   float64
 30  feature_name_feature_22  4967 non-null   float64
 31  feature_name_feature_23  4967 non-null   float64
 32  feature_name_feature_24  4967 non-null   float64
 33  feature_name_feature_25  4967 non-null   float64
 34  feature_name_feature_26  4967 non-null   float64
 35  feature_name_feature_27  4967 non-null   float64
 36  feature_name_feature_28  4967 non-null   float64
 37  feature_name_feature_29  4967 non-null   float64
 38  feature_name_feature_3   4967 non-null   float64
 39  feature_name_feature_30  4967 non-null   float64
 40  feature_name_feature_31  4967 non-null   float64
 41  feature_name_feature_32  4967 non-null   float64
 42  feature_name_feature_33  4967 non-null   float64
 43  feature_name_feature_34  4967 non-null   float64
 44  feature_name_feature_35  4967 non-null   float64
 45  feature_name_feature_36  4967 non-null   float64
 46  feature_name_feature_37  4967 non-null   float64
 47  feature_name_feature_38  4967 non-null   float64
 48  feature_name_feature_39  4967 non-null   float64
 49  feature_name_feature_4   4967 non-null   float64
 50  feature_name_feature_40  4967 non-null   float64
 51  feature_name_feature_5   4967 non-null   float64
 52  feature_name_feature_6   4967 non-null   float64
 53  feature_name_feature_7   4967 non-null   float64
 54  feature_name_feature_8   4967 non-null   float64
 55  feature_name_feature_9   4967 non-null   float64
 56  is_beta_feature          4967 non-null   float64
 57  usage_count              4967 non-null   float64
 58  usage_duration_secs      4967 non-null   float64
dtypes: bool(5), datetime64[ns](1), float64(44), int64(3), object(6)
memory usage: 2.1+ MB

In [219]:
subscription['start_date'] = pd.to_datetime(subscription['start_date'])
subscription['end_date'] = pd.to_datetime(subscription['end_date'])

In [220]:
subscription_cpy = pd.get_dummies(subscription, columns=['plan_tier', 'billing_frequency'], dtype=int)
subscription_cpy.drop(columns=['subscription_id'], inplace=True)
subscription_cpy.sample(2)

,account_id,start_date,end_date,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,...,feature_name_feature_8,feature_name_feature_9,is_beta_feature,usage_count,usage_duration_secs,plan_tier_Basic,plan_tier_Enterprise,plan_tier_Pro,billing_frequency_annual,billing_frequency_monthly
2869,A-6e7827,2023-11-05,NaT,1,49,588,False,True,False,False,...,0.0,0.0,0.0,45.0,13973.0,0,0,1,0,1
1766,A-0cc442,2024-09-01,NaT,45,8955,107460,False,False,False,False,...,0.0,0.0,0.0,41.0,13548.0,0,1,0,0,1

In [221]:
subscription_cpy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 61 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   account_id                 5000 non-null   object
 1   start_date                 5000 non-null   datetime64[ns]
 2   end_date                   486 non-null    datetime64[ns]
 3   seats                      5000 non-null   int64
 4   mrr_amount                 5000 non-null   int64
 5   arr_amount                 5000 non-null   int64
 6   is_trial                   5000 non-null   bool
 7   upgrade_flag               5000 non-null   bool
 8   downgrade_flag             5000 non-null   bool
 9   churn_flag                 5000 non-null   bool
 10  auto_renew_flag            5000 non-null   bool
 11  usage_date                 4967 non-null   datetime64[ns]
 12  error_count                4967 non-null   float64
 13  feature_name_feature_1     4967 non-null   float64
 14  feature_name_feature_10    4967 non-null   float64
 15  feature_name_feature_11    4967 non-null   float64
 16  feature_name_feature_12    4967 non-null   float64
 17  feature_name_feature_13    4967 non-null   float64
 18  feature_name_feature_14    4967 non-null   float64
 19  feature_name_feature_15    4967 non-null   float64
 20  feature_name_feature_16    4967 non-null   float64
 21  feature_name_feature_17    4967 non-null   float64
 22  feature_name_feature_18    4967 non-null   float64
 23  feature_name_feature_19    4967 non-null   float64
 24  feature_name_feature_2     4967 non-null   float64
 25  feature_name_feature_20    4967 non-null   float64
 26  feature_name_feature_21    4967 non-null   float64
 27  feature_name_feature_22    4967 non-null   float64
 28  feature_name_feature_23    4967 non-null   float64
 29  feature_name_feature_24    4967 non-null   float64
 30  feature_name_feature_25    4967 non-null   float64
 31  feature_name_feature_26    4967 non-null   float64
 32  feature_name_feature_27    4967 non-null   float64
 33  feature_name_feature_28    4967 non-null   float64
 34  feature_name_feature_29    4967 non-null   float64
 35  feature_name_feature_3     4967 non-null   float64
 36  feature_name_feature_30    4967 non-null   float64
 37  feature_name_feature_31    4967 non-null   float64
 38  feature_name_feature_32    4967 non-null   float64
 39  feature_name_feature_33    4967 non-null   float64
 40  feature_name_feature_34    4967 non-null   float64
 41  feature_name_feature_35    4967 non-null   float64
 42  feature_name_feature_36    4967 non-null   float64
 43  feature_name_feature_37    4967 non-null   float64
 44  feature_name_feature_38    4967 non-null   float64
 45  feature_name_feature_39    4967 non-null   float64
 46  feature_name_feature_4     4967 non-null   float64
 47  feature_name_feature_40    4967 non-null   float64
 48  feature_name_feature_5     4967 non-null   float64
 49  feature_name_feature_6     4967 non-null   float64
 50  feature_name_feature_7     4967 non-null   float64
 51  feature_name_feature_8     4967 non-null   float64
 52  feature_name_feature_9     4967 non-null   float64
 53  is_beta_feature            4967 non-null   float64
 54  usage_count                4967 non-null   float64
 55  usage_duration_secs        4967 non-null   float64
 56  plan_tier_Basic            5000 non-null   int64
 57  plan_tier_Enterprise       5000 non-null   int64
 58  plan_tier_Pro              5000 non-null   int64
 59  billing_frequency_annual   5000 non-null   int64
 60  billing_frequency_monthly  5000 non-null   int64
dtypes: bool(5), datetime64[ns](3), float64(44), int64(8), object(1)
memory usage: 2.2+ MB

In [222]:
col_to_sum = subscription_cpy.columns.difference(['account_id', 'start_date', 'end_date', 'usage_date'])
subscription_cpy = subscription_cpy.groupby('account_id').agg({
    'start_date': 'min',
    'end_date': 'max',
    'usage_date': 'max',
    **{col: 'sum' for col in col_to_sum}
}).reset_index()

In [223]:
final_df = final_df.merge(subscription_cpy, on='account_id', how='left')

In [224]:
final_df

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats_x,is_trial_x,churn_flag_x,...,is_beta_feature,is_trial_y,mrr_amount,plan_tier_Basic,plan_tier_Enterprise,plan_tier_Pro,seats_y,upgrade_flag,usage_count,usage_duration_secs
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False,...,4.0,2,12603,3,2,5,312,1,535.0,152339.0
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True,...,2.0,0,10004,4,1,3,176,3,355.0,101136.0
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False,...,5.0,1,18286,4,4,7,282,1,821.0,251210.0
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False,...,5.0,1,9275,3,1,3,209,2,382.0,102528.0
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True,...,4.0,1,48761,0,4,5,424,2,579.0,215779.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,A-8ae3fc,Company_495,DevTools,CA,2024-06-28,ads,Pro,9,False,False,...,5.0,1,4447,4,1,3,221,0,402.0,130242.0
496,A-55f257,Company_496,FinTech,US,2023-12-21,organic,Basic,9,False,False,...,6.0,3,12137,2,3,5,188,3,476.0,145972.0
497,A-d26ab4,Company_497,DevTools,UK,2024-11-07,organic,Basic,9,False,True,...,3.0,4,16613,2,4,3,202,0,458.0,121379.0
498,A-712533,Company_498,EdTech,US,2023-07-31,organic,Pro,18,False,False,...,4.0,2,19382,4,4,4,341,1,571.0,180056.0
499,A-781cc0,Company_499,EdTech,US,2024-09-04,organic,Pro,12,False,False,...,7.0,3,18315,6,6,4,265,2,864.0,270008.0

In [225]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 84 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   account_id                            500 non-null    object
 1   account_name                          500 non-null    object
 2   industry                              500 non-null    object
 3   country                               500 non-null    object
 4   signup_date                           500 non-null    object
 5   referral_source                       500 non-null    object
 6   plan_tier                             500 non-null    object
 7   seats_x                               500 non-null    int64
 8   is_trial_x                            500 non-null    bool
 9   churn_flag_x                          500 non-null    bool
 10  churn_date                            352 non-null    datetime64[ns]
 11  refund_amount_usd                     352 non-null    float64
 12  preceding_upgrade_flag                352 non-null    float64
 13  preceding_downgrade_flag              352 non-null    float64
 14  is_reactivation                       352 non-null    float64
 15  reason_code_budget                    352 non-null    float64
 16  reason_code_competitor                352 non-null    float64
 17  reason_code_features                  352 non-null    float64
 18  reason_code_pricing                   352 non-null    float64
 19  reason_code_support                   352 non-null    float64
 20  reason_code_unknown                   352 non-null    float64
 21  feedback_text_missing_features        352 non-null    float64
 22  feedback_text_switched_to_competitor  352 non-null    float64
 23  feedback_text_too_expensive           352 non-null    float64
 24  start_date                            500 non-null    datetime64[ns]
 25  end_date                              312 non-null    datetime64[ns]
 26  usage_date                            500 non-null    datetime64[ns]
 27  arr_amount                            500 non-null    int64
 28  auto_renew_flag                       500 non-null    int64
 29  billing_frequency_annual              500 non-null    int64
 30  billing_frequency_monthly             500 non-null    int64
 31  churn_flag_y                          500 non-null    int64
 32  downgrade_flag                        500 non-null    int64
 33  error_count                           500 non-null    float64
 34  feature_name_feature_1                500 non-null    float64
 35  feature_name_feature_10               500 non-null    float64
 36  feature_name_feature_11               500 non-null    float64
 37  feature_name_feature_12               500 non-null    float64
 38  feature_name_feature_13               500 non-null    float64
 39  feature_name_feature_14               500 non-null    float64
 40  feature_name_feature_15               500 non-null    float64
 41  feature_name_feature_16               500 non-null    float64
 42  feature_name_feature_17               500 non-null    float64
 43  feature_name_feature_18               500 non-null    float64
 44  feature_name_feature_19               500 non-null    float64
 45  feature_name_feature_2                500 non-null    float64
 46  feature_name_feature_20               500 non-null    float64
 47  feature_name_feature_21               500 non-null    float64
 48  feature_name_feature_22               500 non-null    float64
 49  feature_name_feature_23               500 non-null    float64
 50  feature_name_feature_24               500 non-null    float64
 51  feature_name_feature_25               500 non-null    float64
 52  feature_name_feature_26               500 non-null    float64
 53  feature_name_feature_27               500 non-null    float64
 54  feature_name_feature_28               500 non-null    float64
 55  feature_name_feature_29               500 non-null    float64
 56  feature_name_feature_3                500 non-null    float64
 57  feature_name_feature_30               500 non-null    float64
 58  feature_name_feature_31               500 non-null    float64
 59  feature_name_feature_32               500 non-null    float64
 60  feature_name_feature_33               500 non-null    float64
 61  feature_name_feature_34               500 non-null    float64
 62  feature_name_feature_35               500 non-null    float64
 63  feature_name_feature_36               500 non-null    float64
 64  feature_name_feature_37               500 non-null    float64
 65  feature_name_feature_38               500 non-null    float64
 66  feature_name_feature_39               500 non-null    float64
 67  feature_name_feature_4                500 non-null    float64
 68  feature_name_feature_40               500 non-null    float64
 69  feature_name_feature_5                500 non-null    float64
 70  feature_name_feature_6                500 non-null    float64
 71  feature_name_feature_7                500 non-null    float64
 72  feature_name_feature_8                500 non-null    float64
 73  feature_name_feature_9                500 non-null    float64
 74  is_beta_feature                       500 non-null    float64
 75  is_trial_y                            500 non-null    int64
 76  mrr_amount                            500 non-null    int64
 77  plan_tier_Basic                       500 non-null    int64
 78  plan_tier_Enterprise                  500 non-null    int64
 79  plan_tier_Pro                         500 non-null    int64
 80  seats_y                               500 non-null    int64
 81  upgrade_flag                          500 non-null    int64
 82  usage_count                           500 non-null    float64
 83  usage_duration_secs                   500 non-null    float64
dtypes: bool(2), datetime64[ns](4), float64(57), int64(14), object(7)
memory usage: 321.4+ KB

In [226]:
support.sample(2)

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
259,T-13e2c4,A-92a3af,2024-03-17,2024-03-19 23:00:00,71.0,medium,29,5.0,False
1738,T-c0657b,A-9289f6,2023-06-12,2023-06-14 02:00:00,50.0,low,155,NaN,False

In [227]:
support['account_id'].nunique()

492

In [228]:
support['submitted_at'] = pd.to_datetime(support['submitted_at'])
support['closed_at'] = pd.to_datetime(support['closed_at'])

In [229]:
support_cpy = pd.get_dummies(support, columns=['priority'], dtype=int)
support_cpy.drop(columns=['ticket_id'], inplace=True)
support_cpy.sample(2)

,account_id,submitted_at,closed_at,resolution_time_hours,first_response_time_minutes,satisfaction_score,escalation_flag,priority_high,priority_low,priority_medium,priority_urgent
1420,A-44dc83,2024-09-15,2024-09-16 00:00:00,24.0,6,5.0,False,0,1,0,0
1322,A-65c341,2023-10-26,2023-10-28 21:00:00,69.0,25,NaN,False,0,0,0,1

In [230]:
support_cpy = support_cpy.groupby('account_id').agg({
    'submitted_at': ['min', 'max'],
    'closed_at': ['min', 'max'],
    'resolution_time_hours': 'mean',
    'first_response_time_minutes': 'mean',
    'satisfaction_score': 'mean',
    'escalation_flag': 'sum',
    'priority_urgent': 'sum',
    'priority_high': 'sum',
    'priority_low': 'sum',
    'priority_medium': 'sum'})

In [231]:
support_cpy.columns = [
    '_'.join(col).strip() if isinstance(col, tuple) else col
    for col in support_cpy.columns
]

In [232]:
final_df = final_df.merge(support_cpy, on='account_id', how='left')

In [233]:
final_df.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats_x', 'is_trial_x', 'churn_flag_x',
       'churn_date', 'refund_amount_usd', 'preceding_upgrade_flag',
       'preceding_downgrade_flag', 'is_reactivation', 'reason_code_budget',
       'reason_code_competitor', 'reason_code_features', 'reason_code_pricing',
       'reason_code_support', 'reason_code_unknown',
       'feedback_text_missing_features',
       'feedback_text_switched_to_competitor', 'feedback_text_too_expensive',
       'start_date', 'end_date', 'usage_date', 'arr_amount', 'auto_renew_flag',
       'billing_frequency_annual', 'billing_frequency_monthly', 'churn_flag_y',
       'downgrade_flag', 'error_count', 'feature_name_feature_1',
       'feature_name_feature_10', 'feature_name_feature_11',
       'feature_name_feature_12', 'feature_name_feature_13',
       'feature_name_feature_14', 'feature_name_feature_15',
       'feature_name_feature_16', 'feature_name_feature_17',
       'feature_name_feature_18', 'feature_name_feature_19',
       'feature_name_feature_2', 'feature_name_feature_20',
       'feature_name_feature_21', 'feature_name_feature_22',
       'feature_name_feature_23', 'feature_name_feature_24',
       'feature_name_feature_25', 'feature_name_feature_26',
       'feature_name_feature_27', 'feature_name_feature_28',
       'feature_name_feature_29', 'feature_name_feature_3',
       'feature_name_feature_30', 'feature_name_feature_31',
       'feature_name_feature_32', 'feature_name_feature_33',
       'feature_name_feature_34', 'feature_name_feature_35',
       'feature_name_feature_36', 'feature_name_feature_37',
       'feature_name_feature_38', 'feature_name_feature_39',
       'feature_name_feature_4', 'feature_name_feature_40',
       'feature_name_feature_5', 'feature_name_feature_6',
       'feature_name_feature_7', 'feature_name_feature_8',
       'feature_name_feature_9', 'is_beta_feature', 'is_trial_y', 'mrr_amount',
       'plan_tier_Basic', 'plan_tier_Enterprise', 'plan_tier_Pro', 'seats_y',
       'upgrade_flag', 'usage_count', 'usage_duration_secs',
       'submitted_at_min', 'submitted_at_max', 'closed_at_min',
       'closed_at_max', 'resolution_time_hours_mean',
       'first_response_time_minutes_mean', 'satisfaction_score_mean',
       'escalation_flag_sum', 'priority_urgent_sum', 'priority_high_sum',
       'priority_low_sum', 'priority_medium_sum'],
      dtype='object')

In [234]:
final_df.to_csv('final_SaaS_Churning_dataset')

In [235]:
final_df.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats_x', 'is_trial_x', 'churn_flag_x',
       'churn_date', 'refund_amount_usd', 'preceding_upgrade_flag',
       'preceding_downgrade_flag', 'is_reactivation', 'reason_code_budget',
       'reason_code_competitor', 'reason_code_features', 'reason_code_pricing',
       'reason_code_support', 'reason_code_unknown',
       'feedback_text_missing_features',
       'feedback_text_switched_to_competitor', 'feedback_text_too_expensive',
       'start_date', 'end_date', 'usage_date', 'arr_amount', 'auto_renew_flag',
       'billing_frequency_annual', 'billing_frequency_monthly', 'churn_flag_y',
       'downgrade_flag', 'error_count', 'feature_name_feature_1',
       'feature_name_feature_10', 'feature_name_feature_11',
       'feature_name_feature_12', 'feature_name_feature_13',
       'feature_name_feature_14', 'feature_name_feature_15',
       'feature_name_feature_16', 'feature_name_feature_17',
       'feature_name_feature_18', 'feature_name_feature_19',
       'feature_name_feature_2', 'feature_name_feature_20',
       'feature_name_feature_21', 'feature_name_feature_22',
       'feature_name_feature_23', 'feature_name_feature_24',
       'feature_name_feature_25', 'feature_name_feature_26',
       'feature_name_feature_27', 'feature_name_feature_28',
       'feature_name_feature_29', 'feature_name_feature_3',
       'feature_name_feature_30', 'feature_name_feature_31',
       'feature_name_feature_32', 'feature_name_feature_33',
       'feature_name_feature_34', 'feature_name_feature_35',
       'feature_name_feature_36', 'feature_name_feature_37',
       'feature_name_feature_38', 'feature_name_feature_39',
       'feature_name_feature_4', 'feature_name_feature_40',
       'feature_name_feature_5', 'feature_name_feature_6',
       'feature_name_feature_7', 'feature_name_feature_8',
       'feature_name_feature_9', 'is_beta_feature', 'is_trial_y', 'mrr_amount',
       'plan_tier_Basic', 'plan_tier_Enterprise', 'plan_tier_Pro', 'seats_y',
       'upgrade_flag', 'usage_count', 'usage_duration_secs',
       'submitted_at_min', 'submitted_at_max', 'closed_at_min',
       'closed_at_max', 'resolution_time_hours_mean',
       'first_response_time_minutes_mean', 'satisfaction_score_mean',
       'escalation_flag_sum', 'priority_urgent_sum', 'priority_high_sum',
       'priority_low_sum', 'priority_medium_sum'],
      dtype='object')

In [236]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 96 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   account_id                            500 non-null    object
 1   account_name                          500 non-null    object
 2   industry                              500 non-null    object
 3   country                               500 non-null    object
 4   signup_date                           500 non-null    object
 5   referral_source                       500 non-null    object
 6   plan_tier                             500 non-null    object
 7   seats_x                               500 non-null    int64
 8   is_trial_x                            500 non-null    bool
 9   churn_flag_x                          500 non-null    bool
 10  churn_date                            352 non-null    datetime64[ns]
 11  refund_amount_usd                     352 non-null    float64
 12  preceding_upgrade_flag                352 non-null    float64
 13  preceding_downgrade_flag              352 non-null    float64
 14  is_reactivation                       352 non-null    float64
 15  reason_code_budget                    352 non-null    float64
 16  reason_code_competitor                352 non-null    float64
 17  reason_code_features                  352 non-null    float64
 18  reason_code_pricing                   352 non-null    float64
 19  reason_code_support                   352 non-null    float64
 20  reason_code_unknown                   352 non-null    float64
 21  feedback_text_missing_features        352 non-null    float64
 22  feedback_text_switched_to_competitor  352 non-null    float64
 23  feedback_text_too_expensive           352 non-null    float64
 24  start_date                            500 non-null    datetime64[ns]
 25  end_date                              312 non-null    datetime64[ns]
 26  usage_date                            500 non-null    datetime64[ns]
 27  arr_amount                            500 non-null    int64
 28  auto_renew_flag                       500 non-null    int64
 29  billing_frequency_annual              500 non-null    int64
 30  billing_frequency_monthly             500 non-null    int64
 31  churn_flag_y                          500 non-null    int64
 32  downgrade_flag                        500 non-null    int64
 33  error_count                           500 non-null    float64
 34  feature_name_feature_1                500 non-null    float64
 35  feature_name_feature_10               500 non-null    float64
 36  feature_name_feature_11               500 non-null    float64
 37  feature_name_feature_12               500 non-null    float64
 38  feature_name_feature_13               500 non-null    float64
 39  feature_name_feature_14               500 non-null    float64
 40  feature_name_feature_15               500 non-null    float64
 41  feature_name_feature_16               500 non-null    float64
 42  feature_name_feature_17               500 non-null    float64
 43  feature_name_feature_18               500 non-null    float64
 44  feature_name_feature_19               500 non-null    float64
 45  feature_name_feature_2                500 non-null    float64
 46  feature_name_feature_20               500 non-null    float64
 47  feature_name_feature_21               500 non-null    float64
 48  feature_name_feature_22               500 non-null    float64
 49  feature_name_feature_23               500 non-null    float64
 50  feature_name_feature_24               500 non-null    float64
 51  feature_name_feature_25               500 non-null    float64
 52  feature_name_feature_26               500 non-null    float64
 53  feature_name_feature_27               500 non-null    float64
 54  feature_name_feature_28               500 non-null    float64
 55  feature_name_feature_29               500 non-null    float64
 56  feature_name_feature_3                500 non-null    float64
 57  feature_name_feature_30               500 non-null    float64
 58  feature_name_feature_31               500 non-null    float64
 59  feature_name_feature_32               500 non-null    float64
 60  feature_name_feature_33               500 non-null    float64
 61  feature_name_feature_34               500 non-null    float64
 62  feature_name_feature_35               500 non-null    float64
 63  feature_name_feature_36               500 non-null    float64
 64  feature_name_feature_37               500 non-null    float64
 65  feature_name_feature_38               500 non-null    float64
 66  feature_name_feature_39               500 non-null    float64
 67  feature_name_feature_4                500 non-null    float64
 68  feature_name_feature_40               500 non-null    float64
 69  feature_name_feature_5                500 non-null    float64
 70  feature_name_feature_6                500 non-null    float64
 71  feature_name_feature_7                500 non-null    float64
 72  feature_name_feature_8                500 non-null    float64
 73  feature_name_feature_9                500 non-null    float64
 74  is_beta_feature                       500 non-null    float64
 75  is_trial_y                            500 non-null    int64
 76  mrr_amount                            500 non-null    int64
 77  plan_tier_Basic                       500 non-null    int64
 78  plan_tier_Enterprise                  500 non-null    int64
 79  plan_tier_Pro                         500 non-null    int64
 80  seats_y                               500 non-null    int64
 81  upgrade_flag                          500 non-null    int64
 82  usage_count                           500 non-null    float64
 83  usage_duration_secs                   500 non-null    float64
 84  submitted_at_min                      492 non-null    datetime64[ns]
 85  submitted_at_max                      492 non-null    datetime64[ns]
 86  closed_at_min                         492 non-null    datetime64[ns]
 87  closed_at_max                         492 non-null    datetime64[ns]
 88  resolution_time_hours_mean            492 non-null    float64
 89  first_response_time_minutes_mean      492 non-null    float64
 90  satisfaction_score_mean               466 non-null    float64
 91  escalation_flag_sum                   492 non-null    float64
 92  priority_urgent_sum                   492 non-null    float64
 93  priority_high_sum                     492 non-null    float64
 94  priority_low_sum                      492 non-null    float64
 95  priority_medium_sum                   492 non-null    float64
dtypes: bool(2), datetime64[ns](8), float64(65), int64(14), object(7)
memory usage: 368.3+ KB

In [237]:
(final_df['churn_flag_x'] == final_df['churn_flag_y']).all()

np.False_

In [238]:
(final_df['seats_x'] == final_df['seats_y']).all()

np.False_

In [239]:
(final_df['is_trial_x'] == final_df['is_trial_y']).all()

np.False_

In [240]:
final_df.rename(columns={
    'churn_flag_x': 'churn_flag',
    'churn_flag_y': 'past_churn_count',
    'is_trial_x': 'is_trial_current',
    'is_trial_y': 'trial_count'
}, inplace=True)

In [241]:
final_df.drop(columns=['seats_y'], inplace=True)

In [242]:
final_df['signup_date'] = pd.to_datetime(final_df['signup_date'])

In [243]:
def drop_columns(df, features):
    df.drop(columns=features, inplace=True)

In [244]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 95 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   account_id                            500 non-null    object
 1   account_name                          500 non-null    object
 2   industry                              500 non-null    object
 3   country                               500 non-null    object
 4   signup_date                           500 non-null    datetime64[ns]
 5   referral_source                       500 non-null    object
 6   plan_tier                             500 non-null    object
 7   seats_x                               500 non-null    int64
 8   is_trial_current                      500 non-null    bool
 9   churn_flag                            500 non-null    bool
 10  churn_date                            352 non-null    datetime64[ns]
 11  refund_amount_usd                     352 non-null    float64
 12  preceding_upgrade_flag                352 non-null    float64
 13  preceding_downgrade_flag              352 non-null    float64
 14  is_reactivation                       352 non-null    float64
 15  reason_code_budget                    352 non-null    float64
 16  reason_code_competitor                352 non-null    float64
 17  reason_code_features                  352 non-null    float64
 18  reason_code_pricing                   352 non-null    float64
 19  reason_code_support                   352 non-null    float64
 20  reason_code_unknown                   352 non-null    float64
 21  feedback_text_missing_features        352 non-null    float64
 22  feedback_text_switched_to_competitor  352 non-null    float64
 23  feedback_text_too_expensive           352 non-null    float64
 24  start_date                            500 non-null    datetime64[ns]
 25  end_date                              312 non-null    datetime64[ns]
 26  usage_date                            500 non-null    datetime64[ns]
 27  arr_amount                            500 non-null    int64
 28  auto_renew_flag                       500 non-null    int64
 29  billing_frequency_annual              500 non-null    int64
 30  billing_frequency_monthly             500 non-null    int64
 31  past_churn_count                      500 non-null    int64
 32  downgrade_flag                        500 non-null    int64
 33  error_count                           500 non-null    float64
 34  feature_name_feature_1                500 non-null    float64
 35  feature_name_feature_10               500 non-null    float64
 36  feature_name_feature_11               500 non-null    float64
 37  feature_name_feature_12               500 non-null    float64
 38  feature_name_feature_13               500 non-null    float64
 39  feature_name_feature_14               500 non-null    float64
 40  feature_name_feature_15               500 non-null    float64
 41  feature_name_feature_16               500 non-null    float64
 42  feature_name_feature_17               500 non-null    float64
 43  feature_name_feature_18               500 non-null    float64
 44  feature_name_feature_19               500 non-null    float64
 45  feature_name_feature_2                500 non-null    float64
 46  feature_name_feature_20               500 non-null    float64
 47  feature_name_feature_21               500 non-null    float64
 48  feature_name_feature_22               500 non-null    float64
 49  feature_name_feature_23               500 non-null    float64
 50  feature_name_feature_24               500 non-null    float64
 51  feature_name_feature_25               500 non-null    float64
 52  feature_name_feature_26               500 non-null    float64
 53  feature_name_feature_27               500 non-null    float64
 54  feature_name_feature_28               500 non-null    float64
 55  feature_name_feature_29               500 non-null    float64
 56  feature_name_feature_3                500 non-null    float64
 57  feature_name_feature_30               500 non-null    float64
 58  feature_name_feature_31               500 non-null    float64
 59  feature_name_feature_32               500 non-null    float64
 60  feature_name_feature_33               500 non-null    float64
 61  feature_name_feature_34               500 non-null    float64
 62  feature_name_feature_35               500 non-null    float64
 63  feature_name_feature_36               500 non-null    float64
 64  feature_name_feature_37               500 non-null    float64
 65  feature_name_feature_38               500 non-null    float64
 66  feature_name_feature_39               500 non-null    float64
 67  feature_name_feature_4                500 non-null    float64
 68  feature_name_feature_40               500 non-null    float64
 69  feature_name_feature_5                500 non-null    float64
 70  feature_name_feature_6                500 non-null    float64
 71  feature_name_feature_7                500 non-null    float64
 72  feature_name_feature_8                500 non-null    float64
 73  feature_name_feature_9                500 non-null    float64
 74  is_beta_feature                       500 non-null    float64
 75  trial_count                           500 non-null    int64
 76  mrr_amount                            500 non-null    int64
 77  plan_tier_Basic                       500 non-null    int64
 78  plan_tier_Enterprise                  500 non-null    int64
 79  plan_tier_Pro                         500 non-null    int64
 80  upgrade_flag                          500 non-null    int64
 81  usage_count                           500 non-null    float64
 82  usage_duration_secs                   500 non-null    float64
 83  submitted_at_min                      492 non-null    datetime64[ns]
 84  submitted_at_max                      492 non-null    datetime64[ns]
 85  closed_at_min                         492 non-null    datetime64[ns]
 86  closed_at_max                         492 non-null    datetime64[ns]
 87  resolution_time_hours_mean            492 non-null    float64
 88  first_response_time_minutes_mean      492 non-null    float64
 89  satisfaction_score_mean               466 non-null    float64
 90  escalation_flag_sum                   492 non-null    float64
 91  priority_urgent_sum                   492 non-null    float64
 92  priority_high_sum                     492 non-null    float64
 93  priority_low_sum                      492 non-null    float64
 94  priority_medium_sum                   492 non-null    float64
dtypes: bool(2), datetime64[ns](9), float64(65), int64(13), object(6)
memory usage: 364.4+ KB

In [245]:
# class FeatureConstructor(BaseEstimator, TransformerMixin):

#   def n_construction_days(self, df, feature1, feature2, feature3):
#     df = df.copy()
#     df[feature1] = (df[feature2]-df[feature3]).dt.days
#     return df

#   def n_construction(self, df, feature1, feature2, feature3):
#     df = df.copy()
#     df[feature1] = (df[feature2]-df[feature3])
#     return df

#   def d_construction(self, df, feature1, feature2, feature3):
#     df = df.copy()
#     df[feature1] = df[feature2]/df[feature3]
#     return df

#   def add_support_flag(self, df):
#     df = df.copy()
#     df['support_flag'] = (df['resolution_time_hours_mean'] > 0).astype(int)
#     return df

#   def add_support_pressure(self, df):
#     df = df.copy()
#     df['support_pressure'] = (
#         df['priority_urgent_sum'] * 4 +
#         df['priority_high_sum'] * 3 +
#         df['priority_medium_sum'] * 2 +
#         df['priority_low_sum']
#     )
#     return df

#   def add_support_risk(self, df):
#     df = df.copy()
#     df['support_risk'] = 5 - df['satisfaction_score_mean']
#     return df

#   def add_feature_usage_metrics(self, df):
#     df = df.copy()
#     feature_cols = [col for col in df.columns if "feature_name_" in col]
#     df['feature_adoption_score'] = df[feature_cols].sum(axis=1)
#     df['features_used_count'] = (df[feature_cols] > 0).sum(axis=1)
#     return df

#   def add_days_since_last_usage(self, df, date_col='usage_date'):
#     df = df.copy()
#     observation_date = df[date_col].max()
#     df['days_since_last_usage'] = (observation_date - df[date_col]).dt.days
#     return df

In [246]:
class FeatureConstructor(BaseEstimator, TransformerMixin):

    def __init__(self, day_features=None, diff_features=None, ratio_features=None):
        self.day_features = day_features
        self.diff_features = diff_features
        self.ratio_features = ratio_features

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        df = X.copy()
        if self.day_features:
            for new_col, col1, col2 in self.day_features:
                df[new_col] = (df[col1] - df[col2]).dt.days

        if self.diff_features:
            for new_col, col1, col2 in self.diff_features:
                df[new_col] = df[col1] - df[col2]

        if self.ratio_features:
            for new_col, col1, col2 in self.ratio_features:
                df[new_col] = df[col1] / df[col2]

        df['support_flag'] = (df['resolution_time_hours_mean'] > 0).astype(int)

        df['support_pressure'] = (
            df['priority_urgent_sum'] * 4 +
            df['priority_high_sum'] * 3 +
            df['priority_medium_sum'] * 2 +
            df['priority_low_sum']
        )

        df['support_risk'] = 5 - df['satisfaction_score_mean']

        feature_cols = [c for c in df.columns if "feature_name_" in c]
        df['feature_adoption_score'] = df[feature_cols].sum(axis=1)
        df['features_used_count'] = (df[feature_cols] > 0).sum(axis=1)

        observation_date = df['usage_date'].max()
        df['days_since_last_usage'] = (observation_date - df['usage_date']).dt.days

        return df

In [247]:

def select_features(df):
    feature_cols = [col for col in df.columns if "feature_name_" in col]
    leakage_cols = [
    'churn_date',
    'refund_amount_usd',
    'preceding_upgrade_flag',
    'preceding_downgrade_flag',
    'is_reactivation',
    'reason_code_budget',
    'reason_code_competitor',
    'reason_code_features',
    'reason_code_pricing',
    'reason_code_support',
    'reason_code_unknown',
    'feedback_text_missing_features',
    'feedback_text_switched_to_competitor',
    'feedback_text_too_expensive'
    ]
    IDs = ['account_id', 'account_name']
    raw_dates = [
    'signup_date',
    'start_date',
    'end_date',
    'usage_date',
    'submitted_at_min',
    'submitted_at_max',
    'closed_at_min',
    'closed_at_max'
    ]
    features_to_remove = leakage_cols + IDs + raw_dates + feature_cols
    return df.drop(columns=[c for c in features_to_remove if c in df.columns])

select_features_transformer = FunctionTransformer(select_features)

In [248]:
def drop_columns(df):
    return df.drop(columns=['industry','country','referral_source','plan_tier'], errors="ignore")

drop_columns_transformer = FunctionTransformer(drop_columns)

In [249]:
def fill_subscription_duration(df):
    df = df.copy()
    df["subscription_duration_days"] = df["subscription_duration_days"].fillna(df["account_age_days"])
    return df

fill_duration_transformer = FunctionTransformer(fill_subscription_duration)

In [250]:
X = final_df.drop(columns=['churn_flag'])
y = final_df['churn_flag']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [251]:
set_config(transform_output="pandas")
feature_construction = FeatureConstructor(
    day_features=[
        ('account_age_days', 'usage_date', 'signup_date'),
        ('subscription_duration_days', 'end_date', 'start_date'),
        ('ticket_span_days', 'closed_at_max', 'submitted_at_min')
    ],

    diff_features=[
        ('plan_momentum', 'preceding_upgrade_flag', 'preceding_downgrade_flag')
    ],

    ratio_features=[
        ('avg_usage_time', 'usage_duration_secs', 'usage_count'),
        ('reveneu_per_seat', 'arr_amount', 'seats_x')
    ]
)

select_features_transformer = FunctionTransformer(select_features, validate=False)

feature_transformation = ColumnTransformer(
    transformers=[
        ('onehotencoding', OneHotEncoder(sparse_output=False, drop='first'), ['industry', 'country', 'referral_source']),
        ('ordinalencoding', OrdinalEncoder(), ['plan_tier'])],
    remainder='passthrough', verbose_feature_names_out=False)

feature_drop = FunctionTransformer(drop_columns, validate=False)


imputation = ColumnTransformer(
    transformers=[
        ('constant_imputation', SimpleImputer(strategy='constant', fill_value=0), [
            'resolution_time_hours_mean',
            'first_response_time_minutes_mean',
            'escalation_flag_sum',
            'priority_urgent_sum',
            'priority_high_sum',
            'priority_low_sum',
            'priority_medium_sum',
            'support_pressure',
            'ticket_span_days',
            'support_risk']),
        ('median_imputation', SimpleImputer(strategy='median'), ['satisfaction_score_mean']),
        ('subscription_duration_imputation', fill_duration_transformer, ['subscription_duration_days', 'account_age_days'])
    ],
    remainder='passthrough')

In [252]:
pipe = Pipeline([
    ('feature_construction', feature_construction),
    ('feature_selection', select_features_transformer),
    ('feature_transformation', feature_transformation),
    ('feature_drop', feature_drop),
    ('imputation', imputation)
    ])

In [253]:
pipe.fit(X_train)
transformed_X_train = pipe.transform(X_train)
transformed_X_test = pipe.transform(X_test)

In [254]:
transformed_X_test

,constant_imputation__resolution_time_hours_mean,constant_imputation__first_response_time_minutes_mean,constant_imputation__escalation_flag_sum,constant_imputation__priority_urgent_sum,constant_imputation__priority_high_sum,constant_imputation__priority_low_sum,constant_imputation__priority_medium_sum,constant_imputation__support_pressure,constant_imputation__ticket_span_days,constant_imputation__support_risk,...,remainder__upgrade_flag,remainder__usage_count,remainder__usage_duration_secs,remainder__plan_momentum,remainder__avg_usage_time,remainder__reveneu_per_seat,remainder__support_flag,remainder__feature_adoption_score,remainder__features_used_count,remainder__days_since_last_usage
361,44.555556,82.555556,0.0,3.0,1.0,4.0,1.0,21.0,591.0,1.000000,...,2,493.0,160744.0,0.0,326.052738,10332.000000,1,49.0,27,14
73,39.000000,167.000000,0.0,1.0,0.0,1.0,0.0,5.0,510.0,0.000000,...,2,689.0,206138.0,NaN,299.184325,17505.729730,1,69.0,34,2
374,19.000000,26.000000,0.0,1.0,0.0,0.0,0.0,4.0,0.0,1.000000,...,0,233.0,59902.0,0.0,257.090129,6858.461538,1,21.0,14,12
155,37.333333,79.166667,0.0,1.0,1.0,2.0,2.0,13.0,421.0,0.600000,...,2,696.0,214681.0,2.0,308.449713,14929.333333,1,70.0,32,4
104,37.500000,70.000000,0.0,0.0,3.0,2.0,1.0,13.0,566.0,0.666667,...,2,642.0,200375.0,0.0,312.110592,157152.000000,1,68.0,33,32
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
347,30.250000,119.000000,0.0,1.0,1.0,1.0,1.0,10.0,209.0,1.000000,...,1,638.0,187024.0,-1.0,293.141066,16114.838710,1,61.0,32,11
86,30.571429,94.714286,0.0,3.0,1.0,1.0,2.0,20.0,688.0,1.333333,...,1,402.0,114217.0,0.0,284.121891,17493.000000,1,39.0,25,5
75,36.666667,51.666667,0.0,1.0,2.0,0.0,0.0,10.0,194.0,2.000000,...,0,581.0,181056.0,0.0,311.628227,20409.600000,1,59.0,32,8
438,64.250000,79.250000,1.0,1.0,1.0,1.0,1.0,10.0,478.0,0.500000,...,1,296.0,83537.0,0.0,282.219595,9171.000000,1,30.0,19,17
15,24.500000,30.500000,0.0,0.0,1.0,1.0,0.0,4.0,77.0,1.000000,...,2,531.0,170826.0,0.0,321.706215,15854.857143,1,54.0,31,13